name: Reusable user config build

on:
  workflow_call:
    inputs:
      cmake-args:
        required: false
        type: string
        default: ""
        description: "Additional CMake arguments"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
          key: ${{ runner.os }}-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Initialize workspace (west init)
        run: west init -l app

      - name: Update modules (west update)
        run: west update

      - name: Export Zephyr CMake package (west zephyr-export)
        run: west zephyr-export

      - name: Build
        run: |
          west build --cmake-only -b roBa -d build/roBa ${{ inputs.cmake-args }}
          west build -d build/roBa

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: build/roBa/zephyr/zmk.uf2
